# config.yml for wazuh-certs-tool.sh -A
nodes:
  indexer:
    - name: wazuh-indexer-01
      ip: <INDEXER_01_IP>
    - name: wazuh-indexer-02
      ip: <INDEXER_02_IP>
    - name: wazuh-indexer-03
      ip: <INDEXER_03_IP>
  server:
    - name: wazuh-master-01
      ip: <MASTER_IP>
      node_type: master
    - name: wazuh-worker-01
      ip: <WORKER_01_IP>
      node_type: worker
    - name: wazuh-worker-02
      ip: <WORKER_02_IP>
      node_type: worker
  dashboard:
    - name: wazuh-dashboard
      ip: <DASHBOARD_IP>
