# Place inside nginx.conf at the top level (not inside http {})
stream {
    upstream wazuh_enrollment {
        server 10.10.10.21:1515;
    }
    server {
        listen 1515;
        proxy_pass wazuh_enrollment;
    }

    upstream wazuh_reporting {
        hash $remote_addr consistent;
        server 10.10.10.22:1514;
        server 10.10.10.23:1514;
    }
    server {
        listen 1514;
        proxy_pass wazuh_reporting;
    }
}
