# Place inside nginx.conf at the top level (not inside http {})
stream {
    upstream wazuh_enrollment {
        server 192.168.90.115:1515;
    }
    server {
        listen 1515;
        proxy_pass wazuh_enrollment;
    }

    upstream wazuh_reporting {
        hash $remote_addr consistent;
        server 192.168.90.116:1514;
        server 192.168.90.117:1514;
    }
    server {
        listen 1514;
        proxy_pass wazuh_reporting;
    }
}
